run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - unconvert
    - gocritic
    - revive
  disable:
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  revive:
    min-confidence: 0.8
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: unexported-return
      - name: time-naming
      - name: context-as-argument
      - name: context-keys-type

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G404 # Insecure random number source

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - whyNoLint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - revive